###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

   
      

    mysql:
      image: mysql:5.7.22
      container_name: blog-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=blog
        - MYSQL_USER=root
        - MYSQL_PASSWORD=123456
      ports:
        - "8991:3306"

    webserver:
      image: nginx:alpine
      container_name: blog-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8989:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: blog-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini


    
        

